# Generated by Django 3.2.12 on 2022-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picturepath', models.CharField(max_length=256)),
                ('photo', models.ImageField(default='user1.jpg', upload_to='photos')),
            ],
        ),
    ]
