# Generated by Django 3.2.12 on 2022-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bglu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodglu',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], default=1),
        ),
    ]
