# Generated by Django 3.2.12 on 2022-03-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bglu', '0002_alter_bloodglu_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodglu',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
